### ISSUE TITLE
node_config.yml to look more user friendly and less messy

### ISSUE THREAD

**Issue by leeping-ng** [aisingapore/PeekingDuck#123]
Areas for improvement:
- Be able to distinguish between different nodes (add newline?)
- input and output have dash (-) but others do not, it is arranged alphabetically so it can be confusing to see a mix of input/output with the other config settings
- Input and output should not be changed by user (but needs to be here for config to be read)
- Spacing is 2 currently instead of 4 as we are used to (could be a VS code thing instead?)

```
input.live:
  input:
  - source
  input_source: 0
  mirror_image: false
  output:
  - img
  resolution:
    height: 720
    width: 1280
model.yolo:
  MODEL_NODES:
    yolov3:
      inputs:
      - x:0
      outputs:
      - Identity:0
```
